import {
  GET_START_PRODUCTS,
  SEARCH_PRODUCTS,
  GET_REVIEWS,
  GET_PERSONAL_REVIEWS,
  GET_SINGLE_PRODUCT,
  FILTER_PRODUCTS,
} from './queries';
import { ADD_REVIEW } from './mutations';

export {
  ADD_REVIEW,
  GET_START_PRODUCTS,
  SEARCH_PRODUCTS,
  GET_REVIEWS,
  GET_PERSONAL_REVIEWS,
  GET_SINGLE_PRODUCT,
  FILTER_PRODUCTS,
};
